name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # Schedule to run every day at 9 am

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and extract ChromeDriver
        run: |
          curl -LO https://chromedriver.storage.googleapis.com/93.0.4577.15/chromedriver_win32.zip
          7z x chromedriver_win32.zip -oC:\tools
          del chromedriver_win32.zip

      - name: Add ChromeDriver to PATH
        run: |
          echo "::add-path::C:\tools"

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"
