name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manual dispatch event
  schedule:
    - cron: '0 9 * * *'  # Schedule to run every day at 9 am

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome WebDriver
        uses: nanovms/setup-chrome-driver@v1

      - name: Run tests
        run: |
          python -m unittest discover -s ${{ github.workspace }}/tests -p "test_*.py" -t ${{ github.workspace }}
